[package]
name = "to-do-03-rust-with-sqlite"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = "0.30"
rand = "0.8.5"
faker_rand = "0.1"
dialoguer = "0.10"
prettytable = "0.10.0"
druid = "0.8.3"
tokio = { version = "1", features = ["full"] }
im = "15.0.0"
